### ISSUE TITLE
wordpress-nginx - No package matching 'mysql-server' found available, installed or updated

### ISSUE THREAD

**Issue by jacknaguib** [ansible/ansible-examples#217]
```json
"item": ["mysql-server", "MySQL-python", "libselinux-python", "libsemanage-python"], "msg": "No package matching 'mysql-server' found available, installed or updated", "rc": 126, "results": ["No package matching 'mysql-server' found available, installed or updated"]}
```

This is what I see in the wordpress-nginx/roles/mysql/tasks/main.yml

```yaml
- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - mysql-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python
```

I am running RHEL-7.4_HVM-20180103-x86_64-2-Hourly2-GP2 (ami-1987757b) Amazon image
